# Лабораторная работа №1

## Изучение симплекс-метода решения задачи ЛП

## Условие задачи

Требуется найти решение следующей задачи ЛП:

$$F=\textbf{cx}\rightarrow max,$$
$$\textbf{Ax}\leq\textbf{b},$$
$$\textbf{x}\geq 0.$$

Исходные данные согласно варианту 2:

In [11]:
import numpy as np
from IPython.core.display import display

c = np.array([3, 1, 4], dtype=np.float32)
A = np.array([2, 1, 1, 1, 4, 0, 0, 0.5, 1], dtype=np.float32).reshape(3, 3)
b = np.array([6, 4, 1], dtype=np.float32)

display(c, A, b)

array([3., 1., 4.], dtype=float32)

array([[2. , 1. , 1. ],
       [1. , 4. , 0. ],
       [0. , 0.5, 1. ]], dtype=float32)

array([6., 4., 1.], dtype=float32)